# Write your query or mutation here
query {
  home {
    id
    title
    covers {
      id
      title
      description
      image {
        id
        url
        formats
      }
    }
    sections {
        id
        title
    		cover {
          id
          image {
            id
            formats
          }
        }
      	url
    }
  }
}