# Write your query or mutation here
query {
  home {
    id
    title
    covers {
      id
      title
      description
      image {
        id
        url
        formats
      }
    }
    carousel {
        delay
        speed
    }
  }
}